name: Build

on:
  push:
  schedule:
    - cron: '15 * * * *'

jobs:

  build:
    name: Build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          # Since the runner token don't have read access to all packages.
          persist-credentials: false
      
      - id: composer-cache
        run: echo "dir=$(composer config cache-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-satis-${{ hashFiles('**/satis.json') }}
          restore-keys: ${{ runner.os }}-satis-

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Install dependencies
        run: composer install

      - name: Configure package access
        # This must be set globally due to Satis using only the global auth.json. 
        run: composer config --global github-oauth.github.com "${{ secrets.PACKAGE_READ_TOKEN }}"

      - name: Build
        run: composer build -vvv

      - name: Setup deploy credentials
        run: |
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > deploy-ssh-key
          chmod 600 deploy-ssh-key

      - name: Deploy
        if: github.ref_name == 'main'
        run: rsync -e "ssh -i deploy-ssh-key -o StrictHostKeyChecking=no -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa" --archive --verbose public/ satis@wpelevator.com:satis/